### ISSUE TITLE
iOS 7

### ISSUE THREAD

**Issue by pnicholls** [soffes/sspulltorefresh#39]
Hey folks, thanks a bunch for this its been super useful.

Just wondering what I need to do to get this working with iOS 7? 

After SSPullToRefresh finishes loading it seems to mess with (reduces?) the height of the scrollView.

**Comment by kpavankotesh** [comment]
@nickynick I see the issue @mariussoutier mentioned still exists even after I use it in `-viewDidLayoutSubViews` Any solution for this?
