### ISSUE TITLE
You continue to rock, Sam Soffes

### ISSUE THREAD

**Issue by colinta** [soffes/sspulltorefresh#59]
I was raging all day (still am) on a very weird UICollectionView animation bug.

As a side project, I realized that our pull-to-refresh has been shoved under our navigationbar (which animates in and out - which is causing the animation bug, incidentally).

At first I was like *awww wtf, who is messing with the insets what's going on!?* (having been raging for so long, it was impossible to turn off).  `SSPullToRefresh`!?  Bah!

Dropped into the code, saw `defaultContentInset`, set it to the new values, and shit *just works*.

:clap: :clap: :clap: 

Nice work.  Thanks for, at least, making the end of my day enjoyable.  Tomorrow I have to get back to fixing this animation thing, but that's another day!

**Comment by soffes** [comment]
:heart: thanks!
