### ISSUE TITLE
initWithScrollView:delegate: should call initWithFrame: on super, not self

### ISSUE THREAD

**Issue by vadim-fueled** [soffes/sspulltorefresh#60]
Since `initWithScrollView:delegate:` is a de-facto designated initializer it should call designated initializer  of superclass with `super`, not `self`
Explicitly stating that it's a designated initializer with NS_DESIGNATED_INITIALIZER would be nice.

**Comment by vadim-fueled** [comment]
Did this not result in a warning at https://github.com/soffes/sspulltorefresh/blob/3ee6473e1f35c8c1eab8c28c933592141a8a9759/SSPullToRefresh/SSPullToRefreshView.m#L161
which is my original complaint?
The thing is I can't subclass SSPullToRefreshView in Swift without overriding init(frame:) which is odd.

**Comment by soffes** [comment]
Fixed that in 68ac0ee1febdf1e514b128f2c6cd05848fa66828
